openapi: 3.0.3
info:
  title: 스티비 API
  description: |-
    ### 개요
    스티비에서 제공하는 API에 대한 요청 및 응답 방법을 확인할 수 있는
    문서입니다.
    ### Base URL
    모든 API 요청의 base URL은 https://api.stibee.com/v2 입니다.
    ```javascript
    이메일 목록 조회 예시
    GET https://api.stibee.com/v2/emails
    ```
    ### 인증
    모든 API 요청은 인증을 위해 AccessToken 헤더를 필요로 합니다.
    AccessToken은 스티비 서비스의 [워크스페이스 설정] > [API 키]에서 생성할 수 있습니다. ([스티비 도움말> 주소록 API 사용하기 > API 키 만들기](https://help.stibee.com/api-webhook/list-api#id-1-api))
    ```HTML
    GET /emails
    AccessToken: abcdefg1234
    ```
    ### 오류 응답
    서버가 정상적으로 운영되는 상황에서는 `200 OK`와 `400 Bad Request`만 응답됩니다. 이외의 `5XX` 응답코드에 대해서는 장애 상황으로 인지하여 재시도 등의 처리를 해야합니다.
    API 요청 시 실패에 대한 400 코드 오류의 형태는 다음과 같습니다.
    ```JSON
    {
      "code":"Errors.Data.InvalidRequest",
      "httpStatusCode":400,
      "message":"잘못된 요청입니다."
    }
    ```
    ### 포맷 
    쿼리 스트링으로 요청되는 값을 제외한 모든 본문 요청은 JSON 타입이며 인코딩은 UTF-8입니다.
  termsOfService: https://policy.stibee.com/terms
  contact:
    email: dev@stibee.com
  version: 2.0.0
externalDocs:
  description: webhook api 문서
  url: https://help.stibee.com/hc/ko/articles/4756496712079-%EC%A3%BC%EC%86%8C%EB%A1%9D-%EC%9B%B9%ED%9B%85-Webhook-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
servers:
  - url:  https://qa-api.stibee.com/v2

operationsSorter: 'alpha'

security:
  - AccessToken: []

tags:
  - name: "이메일"
  - name: "이메일 - 콘텐츠"
  - name: "이메일 - 태그"
  - name: "이메일 - 발송"
  - name: "주소록"
  - name: "주소록 - 구독자"
  - name: "주소록 - 그룹"
  - name: "주소록 - 발신자 이메일 주소"
  - name: "주소록 - 사용자 정의 필드"
    externalDocs:
      description: Find out more
      url: http://swagger.io
      
  # get:
  #     tags:
  #       - 주소록
  #     parameters:
  #       - name: ""
  #         in: query
  #         required: true
  #         schema:
  #           type: integer
  #           format: int
  #     responses:
  #       '200':
  #         description: ""
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/CreateListResponse'
paths:
  /emails:
    post:
      summary: 이메일 생성
      tags:
        - 이메일
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmailRequest'
            example:
              subject: "Email Subject"
              senderEmail: "sender@example.com"
              senderName: "Sender Name"
      responses:
        '200':
          description: "200 OK"
    get:
      summary: 이메일 목록 조회
      tags:
        - 이메일
      parameters:
        - name: tagId
          in: query
          required: false
          schema:
            type: integer
            format: int
        - name: listId
          in: query
          required: false
          schema:
            type: integer
            format: int
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int
            default: 20
      responses:
        '200':
          description: "200 OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEmailsResponse'

  /emails/{id}:
    get:
      summary: 이메일 정보 조회
      tags:
        - 이메일
      parameters:
        - name: id
          in: path
          required: true
          description: 이메일 아이디
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEmailResponse'
    put:
      tags:
        - 이메일
      summary: 이메일 정보 수정
      description: |
        작성 중 상태인 이메일의 정보(이메일 제목, 발신자 이름, 세그먼트, 그룹 등)를 수정할 수 있습니다.
      parameters:
        - name: id
          in: path
          required: true
          description: 수정할 이메일 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmailRequest'
      responses:
        '200':
          description: 이메일이 성공적으로 수정됨
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateEmailErrorResponse'
    delete:
      summary: 이메일 삭제
      tags:
        - 이메일
      parameters:
        - name: deletedEmailId
          in: path
          required: true
          description: 삭제할 이메일 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 성공적으로 삭제됨
  /emails/{id}/logs:
    get:
      tags:
        - 이메일
      summary: 이메일 상세 통계 조회
      description: 특정 이메일의 상세 통계 정보를 조회합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 이메일 아이디
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: 페이징 처리를 위한 인덱스
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          required: false
          description: offset부터 보여질 아이템 최대 개수
          schema:
            type: integer
            minimum: 1
            default: 100
      responses:
        '200':
          description: 상세 통계 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailLogsResponse'
  /emails/{id}/copy:
    post:
      tags:
        - 이메일
      summary: 이메일 복사
      description: 특정 이메일을 복사하여 새로운 이메일을 생성합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 복사할 이메일 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 이메일이 성공적으로 복사됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedCopiedEmailResponse'
  /emails/{id}/tags/release:
    post:
      tags:
        - "이메일 - 태그"
      summary: 이메일 태그 해제
      description: 특정 이메일에서 지정된 태그들을 해제합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 이메일 아이디
          schema:
            type: integer
        - name: tagIds
          in: query
          required: true
          description: 태그 아이디 목록 (콤마로 구분)
          schema:
            type: string
            pattern: '^\d+(,\d+)*$'
            example: "1,2"
      responses:
        '200':
          description: 성공적으로 태그가 해제됨
  /emails/{id}/tags/assign:
    post:
      summary: 이메일 태그 할당
      tags:
        - "이메일 - 태그"
      parameters:
        - name: id
          in: path
          required: true
          description: 이메일 아이디
          schema:
            type: integer
        - name: tagIds
          in: query
          required: true
          description: 태그 아이디 목록 (콤마로 구분)
          schema:
            type: string
          example: "1,2"
            
      responses:
        '200':
          description: 성공적으로 처리됨
        '400':
          description: 잘못된 요청
        '404':
          description: 이메일을 찾을 수 없음
  
  
  /emails/{id}/content:
    get:
      tags:
        - "이메일 - 콘텐츠"
      summary: 이메일 콘텐츠 조회
      description: 특정 이메일의 HTML 콘텐츠를 조회합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 이메일 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 이메일 콘텐츠
          content:
            text/html:
              schema:
                type: string
                example: |
                  <html>
                    <head>
                    </head>
                    <body>
                      hello
                    </body>
                  </html>
    post:
      summary: 이메일 콘텐츠 수정
      tags:
        - "이메일 - 콘텐츠"
      parameters:
        - name: id
          in: path
          required: true
          description: 이메일 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          text/html:
            schema:
              type: string
              description: 이메일 HTML 콘텐츠
            example: |
              <html>
                <head>
                </head>
                <body>
                  hello
                </body>
              </html>
      responses:
        '200':
          description: 성공적으로 처리됨
  /emails/{id}/send:
    post:
      tags:
        - "이메일 - 발송"
      summary: 이메일 발송
      description: 특정 이메일을 발송합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 발송할 이메일 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 이메일이 성공적으로 발송됨
  /emails/{id}/reserve:
    post:
      tags:
        - "이메일 - 발송"
      summary: 이메일 발송 예약
      description: |
        발송 시간을 YYYYMMDDhhmmss 형식으로 지정해 예약합니다.
        대한민국 표준시(UTC+9)를 따릅니다.
        예시: 2024년 7월 22일 11시 30분 00초 → 20240722113000
      parameters:
        - name: id
          in: path
          required: true
          description: 예약 발송할 이메일 아이디
          schema:
            type: integer
        - name: reserveTime
          in: query
          required: true
          description: |
            예약 발송 시간 (YYYYMMDDhhmmss 형식)
            대한민국 표준시(UTC+9) 기준
          schema:
            type: string
            pattern: '^\d{14}$'
            example: "20240722113000"
      responses:
        '200':
          description: 이메일 발송이 성공적으로 예약됨
  /emails/{id}/cancel-reserve:
    post:
      tags:
        - "이메일 - 발송"
      summary: 이메일 발송 예약 취소
      description: 예약된 이메일 발송을 취소합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 예약 취소할 이메일 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 이메일 발송 예약이 성공적으로 취소됨
  /lists:
    post:
      tags:
        - 주소록
      summary: 주소록 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateListRequest'
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateListResponse'
    get:
      tags:
        - 주소록
      summary: 주소록 목록 조회
      parameters:
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int
            default: 50
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListsResponse'
  /lists/{id}:
    get:
      summary: 주소록 정보 조회
      tags:
        - 주소록
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 성공적으로 조회됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListResponse'
              example:
                id: 1234
                owner: "hello@stibee.com"
                name: "스티비 뉴스레터"
                senderName: "스티비"
                companyName: "스티비 주식회사"
                companyContact: "hello@stibee.com"
                companyAddress: "서울시 중구 동호로17길 13, 4층"
                useSubscriberAutoDelete: true
                canSendToUnsubscribed: false
    put:
      summary: 주소록 정보 수정
      tags:
        - 주소록
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateListRequest'
            example:
              name: "스티비 뉴스레터"
              senderName: "스티비"
              companyName: "스티비 주식회사"
              companyContact: "support@stibee.com"
              companyAddress: "서울시 중구 동호로17길 13, 4층"
              useSubscriberAutoDelete: true
              canSendToUnsubscribed: false
      responses:
        '200':
          description: 성공적으로 수정됨
    delete:
      tags:
        - 주소록
      summary: 주소록 삭제
      description: 특정 아이디의 주소록을 삭제합니다
      parameters:
        - name: listId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공적으로 삭제됨
  /lists/{id}/subscribers/count:
    get:
      summary: 주소록 구독자 수 조회
      tags:
        - 주소록
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 성공적으로 조회됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSubscriberCountResponse'
    
    
                
  # /lists/{id}/fields:
  #   get:
  #     tags:
  #       - 주소록
  #     summary: 주소록 사용자 정의 필드 조회
  #     description: 특정 주소록의 사용자 정의 필드 목록을 조회합니다
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         description: 주소록 아이디
  #         schema:
  #           type: integer
  #     responses:
  #       '200':
  #         description: 사용자 정의 필드 목록
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/GetSubscribersVarsResponse'
  #   post:
  #     tags:
  #       - 주소록
  #     summary: 주소록 사용자 정의 필드 생성
  #     description: 특정 주소록에 새로운 사용자 정의 필드를 생성합니다
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         description: 주소록 아이디
  #         schema:
  #           type: integer
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/CreateSubscriberVarRequest'
  #     responses:
  #       '200':
  #         description: 성공적으로 생성됨
  /lists/{id}/senders:
    post:
      tags:
        - "주소록 - 발신자 이메일 주소"
      summary: 밣신자 이메일 주소 추가
      description: |
        발신자 이메일 주소를 추가합니다. 
        인증 이메일이 발송되고, 그 이메일에서 인증을 하면 추가됩니다. 
        워크스페이스 단위에서 한번 인증한 이메일 주소는 다른 주소록에 추가할 때 인증 이메일이 발송되지 않고 바로 추가됩니다.
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddSenderRequest'
      responses:
        '200':
          description: 성공적으로 발신자 이메일이 추가됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddSenderResponse'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddSenderErrorResponse'
    get:
      summary: 발신자 이메일 주소 목록 조회
      tags:
        - "주소록 - 발신자 이메일 주소"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 발신자 이메일 주소 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetListSenderResponse'
              example:
                - email: "gildong.go@stibee.com"
                  authorized: false
  /lists/{id}/senders/{email}/verify:
    post:
      tags:
        - "주소록 - 발신자 이메일 주소"
      summary: 발신자 이메일 주소 인증 이메일 발송 요청
      description: |
        주소록에 이미 추가된 발신자 이메일 주소에 대해 인증 이메일 발송을 다시 요청할 수 있습니다.
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: email
          in: path
          required: true
          description: 발신자 이메일 주소
          schema:
            type: string
            format: email
      responses:
        '200':
          description: 인증 이메일이 성공적으로 발송됨
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSenderVerificationErrorResponse'
  /lists/{id}/subscribers:
    post:
      summary: 구독자 추가
      tags:
        - "주소록 - 구독자"
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddSubscriberRequest'
            example:
              subscriber:
                email: "gildong.go@stibee.com"
                status: "subscribed"
                fields:
                  name: "고길동"
                  age: 45
              updateEnabled: true
      responses:
        '200':
          description: 구독자 업데이트 성공
        '201':
          description: 구독자 추가 성공
        '400':
          description: 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InvalidSubscriberVar:
                  description: "추가 실패 - 사용자 정의 필드가 잘못됨."
                  value:
                    code: "stberror.Errors.List.InvalidSubscriberVar"
                    httpStatusCode: 400
                AlreadyExistEmail:
                  description: "(update가 false인 경우) 추가 실패 - 주소록에 이미 추가된 구독자임. "
                  value:
                    code: "stberror.Errors.List.AlreadyExistEmail"
                    httpStatusCode: 400
                InvalidEmail:
                  description: "추가 실패 - 이메일 주소 형식이 잘못됨."
                  value:
                    code: "stberror.Errors.List.InvalidEmail"
                    httpStatusCode: 400
                InvalidData:
                  description: "추가 실패 - 사용자 정의 필드가 잘못됨."
                  value:
                    code: "stberror.Errors.List.InvalidData"
                    httpStatusCode: 400
    get:
      summary: 구독자 목록 조회
      tags:
        - "주소록 - 구독자"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: 페이징 처리를 위한 인덱스
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: limit
          in: query
          required: false
          description: |
            offset부터 보여질 아이템 최대 개수
            * 조회된 아이템의 최대 개수는 1000을 넘을 수 없다.
          schema:
            type: integer
            default: 100
            maximum: 1000
      responses:
        '200':
          description: 성공적으로 조회됨
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetSubscribersResponse'
              example:
                - email: "gildong@stibee.com"
                  status: "subscribed"
                  fields:
                    $ad_agreed: ""
                    age: "45"
                    name: "고길동"
                  createdTime: "2024-11-12 17:09:13 +0900 KST"
                  modifiedTime: "2024-11-17 20:01:11 +0900 KST"
        '400':
          description: 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InvalidSubscriberVar:
                  description: "한번에 요청할 수 있는 범위를 초과하였음.."
                  value:
                    code: "stberror.Errors.Data.LimitExceeded"
                    httpStatusCode: 400
    delete:
      summary: 구독자 완전 삭제
      tags:
        - "주소록 - 구독자"
      parameters:
        - name: listid
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteSubscribersRequest'
      responses:
        '200':
          description: 구독자 삭제 성공
        '400':
          description: 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                LimitExceeded:
                  description: "한번에 너무 많은 구독자를 요청함. (최대 1,000명)"
                  value:
                    code: "stberror.Errors.List.LimitExceeded"
                    httpStatusCode: 400
                TooLongData:
                  description: "한번에 너무 많은 본문을 요청함. (최대 10MB)"
                  value:
                    code: "stberror.Errors.List.TooLongData"
                    httpStatusCode: 400
  /lists/{id}/subscribers/double-optin:
    post:
      summary: 구독자 추가 - 구독 확인 이메일 발송
      tags:
        - "주소록 - 구독자"
      description: |
        인증 이메일 발송 및 구독자 추가 API는 구독자가 주소록에 존재하지 않는 상태에서 '구독 대기' 상태로 
        주소록에 추가되며 인증메일이 구독자에게 발송된다. 구독확인 메일을 수신한 구독자가 인증을 마치면 
        '구독 중' 상태로 전환된다.
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendDoubleOptinRequest'
            example:
              subscriber:
                email: "gildong.go@stibee.com"
                fields:
                  name: "고길동"
                  age: 45
      responses:
        '200':
          description: 구독 확인 이메일 발송 성공
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InvalidSubscriberVar:
                  description: "추가 실패 - 사용자 정의 필드가 잘못됨."
                  value:
                    code: "stberror.Errors.List.InvalidSubscriberVar"
                    httpStatusCode: 400
                AlreadyExistEmail:
                  description: "(update가 false인 경우) 추가 실패 - 주소록에 이미 추가된 구독자임. "
                  value:
                    code: "stberror.Errors.List.AlreadyExistEmail"
                    httpStatusCode: 400
                InvalidEmail:
                  description: "추가 실패 - 이메일 주소 형식이 잘못됨."
                  value:
                    code: "stberror.Errors.List.InvalidEmail"
                    httpStatusCode: 400
                InvalidData:
                  description: "추가 실패 - 사용자 정의 필드가 잘못됨."
                  value:
                    code: "stberror.Errors.List.InvalidData"
                    httpStatusCode: 400
  /lists/{id}/subscribers/batch:
    post:
      tags:
        - "주소록 - 구독자"
      summary: 주소록 구독자 대량 추가
      description: 주소록에 여러 구독자를 한 번에 추가합니다
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: update
          in: query
          required: false
          description: |
            구독자가 이미 존재할 경우 업데이트 여부
            - false: 업데이트하지 않음
            - true: 이메일 주소 외 다른 값들을 새로 요청한 값으로 업데이트함
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchSubscriberRequest'
      responses:
        '200':
          description: 구독자 추가 결과
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchSubscriberResponse'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchSubscriberErrorResponse'
    
  /lists/{id}/subscribers/{subscriber}:
    put:
      summary: 구독자 정보 수정
      tags:
       - "주소록 - 구독자"
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: subscriber
          in: path
          required: true
          description: 구독자 이메일 주소
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriberRequest'
      responses:
        '200':
          description: 성공적으로 수정됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriberResponse'
              example:
                createdSubscribers: ["0@monitor.stibee.com"]
                updatedSubscribers: ["1@monitor.stibee.com"]
                failNoEmails: null
                failInvalidEmails: null
                failDuplicatedEmails: null
                failInvalidFields: null
                failInvalidSubscriberStatus: null
                failAlreadyExists: null
  /lists/{id}/subscribers/{subscriberEmail}/unsubscribe:
    post:
      summary: 구독자 수신거부
      tags:
       - "주소록 - 구독자"
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: subscriberEmail
          in: path
          required: true
          description: 구독자 이메일 주소
          schema:
            type: string
            format: email
      responses:
        '200':
          description: 성공적으로 수신거부 처리됨
  /lists/{id}/groups/{groupId}/assign:
    post:
      summary: 구독자 그룹 할당
      tags:
       - "주소록 - 구독자"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: groupId
          in: path
          required: true
          description: 그룹 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignGroupRequest'
      responses:
        '200':
          description: 그룹 할당 성공
  /lists/{id}/groups/{groupId}/release:
    post:
      summary: 구독자 그룹 해제
      tags:
       - "주소록 - 구독자"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: groupId
          in: path
          required: true
          description: 그룹 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReleaseGroupRequest'
      responses:
        '200':
          description: 그룹 해제 성공
  /lists/{id}/senders/{email}:
    delete:
      summary: 발신자 이메일 주소 삭제
      tags:
        - "주소록 - 발신자 이메일 주소"
      parameters:
        - name: id
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: email
          in: path
          required: true
          description: 발신자 이메일 주소
          schema:
            type: string
            format: email
      responses:
        '200':
          description: 발신자 이메일 주소 삭제 성공
  /lists/{id}/groups:
    post:
      summary: 그룹 생성
      tags:
        - "주소록 - 그룹"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroupRequest'
      responses:
        '200':
          description: 그룹 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGroupResponse'
    get:
      summary: 그룹 목록 조회
      tags:
        - "주소록 - 그룹"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: 페이징 처리를 위한 인덱스
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          required: false
          description: offset부터 보여질 아이템 최대 개수
          schema:
            type: integer
            minimum: 1
            default: 10
        - $ref: '#/components/parameters/SortByParam'
        - $ref: '#/components/parameters/OrderByParam'
      responses:
        '200':
          description: 그룹 목록 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGroupResponse'
  /lists/{id}/groups/{groupId}:
    put:
      summary: 그룹 정보 수정
      tags:
        - "주소록 - 그룹"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: groupId
          in: path
          required: true
          description: 그룹 아이디
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGroupRequest'
      responses:
        '200':
          description: 그룹 정보 수정 성공
    delete:
      summary: 그룹 삭제
      tags:
        - "주소록 - 그룹"
      parameters:
        - name: listId
          in: path
          required: true
          description: 주소록 아이디
          schema:
            type: integer
        - name: groupId
          in: path
          required: true
          description: 그룹 아이디
          schema:
            type: integer
      responses:
        '200':
          description: 그룹 삭제 성공
    
##############################################################################################

components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: AccessToken
      in: header
      description: Access token for use this api
  parameters:
    SortByParam:
      name: sortBy
      in: query
      required: false
      description: |
        정렬 기준
        * id: 그룹 아이디
        * name: 그룹 이름
      schema:
        type: string
        enum: [id, name]
        default: id
    OrderByParam:
      name: orderBy
      in: query
      required: false
      description: |
        정렬 방향
        * desc: 내림차순
        * asc: 오름차순
      schema:
        type: string
        enum: [desc, asc]
        default: desc
  schemas:
    # SampleSchema:
    #   type: object
    #   required:
    #     - fdddddddddd
    #   properties:
    #     properties1:
    #       type: string
    #       description: 기본 필드
    #       example: 예시
    #       default: "가나다"
    CreateListRequest:
      type: object
      required: 
        - name
        - senderName
        - companyName
        - companyContact
        - companyAddress
      properties:
        name:
          type: string
          description: 주소록 이름
          example: 스티비 뉴스레터
        senderName:
          type: string
          description: 발신자 이름
          example: 스티비
        companyName:
          type: string
          description: 회사 이름
          example: 스티비 주식회사
        companyContact:
          type: string
          description: 회사 연락처
          example: support@stibee.com
        companyAddress:
          type: string
          description: 회사 주소
          example: 서울시 중구 동호로17길 13, 4층
        useSubscriberAutoDelete:
          type: boolean
          description: 하드바운드 시 구독자 자동삭제 여부
          default: true
          example: true
        canSendToUnsubscribed:
          type: boolean
          description: "이메일 발송 시 수신거부 구독자 포함 가능 여부"
          default: false
          example: false
    CreateListResponse:
      type: object
      properties:
        id:
          type: integer
          description: "주소록 아이디"
          example: 1234
    GetListsResponse:
      type: object
      properties:
        id:
          type: integer
          description: 주소록 아이디
          example: 1234
        owner:
          type: string
          description: ""
          example: "hello@stibee.com"
        name:
          type: string
          description: 주소록 이름
          example: 1234
        senderName:
          type: string
          description: 발신자 이름
          example: 스티비
        companyName:
          type: string
          description: 회사 이름
          example: 스티비 주식회사
          default: 스티비
        companyContact:
          type: string
          description: 회사 연락처
          example: support@stibee.com
        companyAddress:
          type: string
          description: 회사 주소
          example: 서울시 중구 동호로17길 13, 4층
        useSubscriberAutoDelete:
          type: boolean
          description: 하드바운드 시 구독자 자동삭제 여부
          example: true
        canSendToUnsubscribed:
          type: boolean
          description: "이메일 발송 시 수신거부 구독자 포함 가능 여부"
          example: false
          
    GetEmailsResponse:
      type: object
      properties:
        total:
          type: integer
          description: 기본 필드
          example: 8
        offset:
          type: integer
          description: 기본 필드
          example: 0
        limit:
          type: integer
          description: 기본 필드
          example: 8
        items:
          type: array
          items:
            $ref: '#/components/schemas/GetEmailResponse'
    GetEmailResponse:
      type: object
      properties:
        id:
          type: integer
          description: 이메일 아이디
          example: 123456
        status:
          type: integer
          description: |
            이메일의 상태 코드
            - 0: 작성 중
            - 1: 예약 중
            - 21, 22: 발송 중
            - 3: 발송 완료
          enum:
            - 0
            - 1
            - 21
            - 22
            - 3
          example: 3
        listId:
          type: integer
          description: 주소록 아이디
          example: 123456
        type:
          type: integer
          description: 이메일의 타입
          example: 1
        subType:
          type: integer
          description: 이메일의 서브 타입
          example: 0
        subject:
          type: string
          description: 이메일 제목
          example: "이메일 제목"
        subjectA:
          type: string
          description: A/B 테스트의 A 제목
          example: ""
        subjectB:
          type: string
          description: A/B 테스트의 B 제목
          example: ""
        permanentLink:
          type: string
          format: uri
          description: 이메일 콘텐츠 링크(웹에서 보기)
          example: "https://stib.ee/2eYF"
        permanentLinkSecondary:
          type: string
          format: uri
          description: ""
          example: "https://stib.ee/2eYF"
        segmentIds:
          type: array
          description: "" 
          items:
            type: integer
          example: [1234]
        groupIds:
          type: array
          description: ""
          items:
            type: integer
          nullable: true
          example: null
        sentTime:
          type: string
          format: date-time
          description: 이메일 발송 시간
          example: "2024-07-23T18:43:03+09:00"
        sentTimeA:
          type: string
          format: date-time
          description: A/B 테스트의 A 발송 시간
          example: "0001-01-01T00:00:00Z"
        sentTimeB:
          type: string
          format: date-time
          description: A/B 테스트의 B 발송 시간
          example: "1990-01-01T00:00:00+09:00"
        senderEmail:
          type: string
          format: email
          description: 발신자 이메일 주소
          example: "gildong.go@stibee.com"
        senderName:
          type: string
          description: 발신자 이름
          example: "Gildong"
        senderNameA:
          type: string
          description: A/B 테스트의 A 발신자 이름
          example: ""
        senderNameB:
          type: string
          description: A/B 테스트의 B 발신자 이름
          example: ""
        owner:
          type: string
          format: uuid
          description: 이메일 소유자 UU아이디
          example: "hello@stibee.com"
        abRatio:
          type: integer
          description: A/B 테스트의 비율
          example: 0
        isStarred:
          type: boolean
          description: 즐겨찾기 여부
          example: false
        includeUnsubscribed:
          type: boolean
          description: 구독 취소한 사용자 포함 여부
          example: false
        createdTime:
          type: string
          format: date-time
          description: 이메일 생성 시간
          example: "2024-07-19T17:56:06+09:00"
        modifiedTime:
          type: string
          format: date-time
          description: 이메일 수정 시간
          example: "2024-07-23T18:43:18+09:00"
    GetSubscribersVarsResponse:
      type: array
      items:
        $ref: '#/components/schemas/GetSubscriberVarsResponse'
      example:
        - id: 60723
          label: "이메일 주소"
          substitution: "email"
          defaultValue: ""
          isMandatory: true
          customLabel: ""
          type: "text"
          typeOption: {}
          isVisible: false
        - id: 60724
          label: "이름"
          substitution: "name"
          defaultValue: ""
          isMandatory: false
          customLabel: ""
          type: "text"
          typeOption: {}
          isVisible: false
    GetSubscriberVarsResponse:
      type: object
      properties:
        id:
          type: integer
          description: 사용자 정의 필드 아이디
        label:
          type: string
          description: 구독 화면 등에 노출되는 사용자 정의 필드 이름
        substitution:
          type: string
          description: 메일머지 치환자를 입력하거나 구독자 정보를 API로 전송할 때 사용하는 값
        defaultValue:
          type: string
          description: 메일머지 치환자를 구독자 정보로 치환할 때, 저장된 값이 없을 때 사용하는 값
        isMandatory:
          type: boolean
          description: 필수 값 여부
        customLabel:
          type: string
          description: 구독 화면에서 표시할 사용자 정의 필드 이름
        type:
          type: string
          description: 사용자 정의 필드 유형(예. 텍스트, 드롭다운)
        typeOption:
          type: object
          description: 사용자 정의 필드 유형에 따른 부가 옵션
        isVisible:
          type: boolean
          description: 필드 표시 여부
    CreateSubscriberVarRequest:
      type: object
      required:
        - label
        - substitution
        - defaultValue
        - isMandatory
        - type
      properties:
        label:
          type: string
          description: 구독 화면 등에 노출되는 사용자 정의 필드 이름
          example: "Address"
        substitution:
          type: string
          description: 메일머지 치환자를 입력하거나 구독자 정보를 API로 전송할 때 사용하는 값
          example: "addr"
        defaultValue:
          type: string
          description: 메일머지 치환자를 구독자 정보로 치환할 때, 저장된 값이 없을 때 사용하는 값
          example: ""
        isMandatory:
          type: boolean
          description: 필수 값 여부
          example: false
        type:
          type: string
          description: 사용자 정의 필드 유형(예. 텍스트, 드롭다운)
          example: "text"
    CreatedCopiedEmailResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: 복사된 이메일 아이디
          example: 60001
    AddSenderRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          description: 발신자 이메일 주소
          format: email
          example: "gildong.go@stibee.com"
    AddSenderResponse:
      type: object
      required:
        - authorized
      properties:
        authorized:
          type: boolean
          description: |
            추가하는 발신자 이메일의 인증 여부. 
            false이면 발신자 이메일 주소로 인증 이메일이 발송됨. 
            true이면 발송되지 않고 바로 추가됨.
          example: false
    AddSenderErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum: 
            - stberror.Errors.List.NotPermittedSenderDomain
          description: 에러 코드
          example: "stberror.Errors.List.NotPermittedSenderDomain"
        httpStatusCode:
          type: integer
          description: 상태 코드
          example: 400
        message:
          type: string
          description: 에러 메시지
          example: "발신자 이메일 주소로 사용할 수 없는 도메인으로 추가를 시도함. (gmail.com, naver.com 등)"
    Subscriber:
      type: object
      required:
        - $status
        - email
      properties:
        $status:
          type: string
          enum: [S, D]
          description: |
            구독자 상태
            - S: 구독 중
            - D: 수신거부
        email:
          type: string
          format: email
          description: 구독자 이메일 주소
        name:
          type: string
          description: 구독자 이름 (사용자 정의 필드)
        age:
          type: integer
          description: 구독자 나이 (사용자 정의 필드)
      additionalProperties:
        description: 주소록에 생성된 기타 사용자 정의 필드별 값
    BatchSubscriberRequest:
      type: object
      required:
        - subscribers
      properties:
        subscribers:
          type: array
          items:
            $ref: '#/components/schemas/Subscriber'
          maxItems: 1000
          description: 추가할 구독자 목록 (최대 1,000명)
    BatchSubscriberResponse:
      type: object
      properties:
        createdSubscribers:
          type: array
          items:
            type: string
          description: 추가 성공한 이메일 주소 목록
          example: ["0@monitor.stibee.com"]
        updatedSubscribers:
          type: array
          items:
            type: string
          description: |
            (update가 true인 경우) 업데이트 성공
            주소록에 이미 추가된 구독자임. 이메일 주소와 구독 상태 외의 다른 정보를 업데이트함
          example: ["1@monitor.stibee.com"]
        failAlreadyExists:
          type: array
          items:
            type: string
          description: |
            (update가 false인 경우) 추가 실패
            주소록에 이미 추가된 구독자임
          nullable: true
        failNoEmails:
          type: array
          items:
            type: string
          description: "추가 실패 - 이메일 주소 필드에 값이 없음"
          nullable: true
        failInvalidEmails:
          type: array
          items:
            type: string
          description: "추가 실패 - 이메일 주소 형식이 잘못됨"
          nullable: true
        failDuplicatedEmails:
          type: array
          items:
            type: string
          description: "추가 실패 - 요청 내 중복된 이메일 주소가 있음"
          nullable: true
        failInvalidFields:
          type: array
          items:
            type: string
          description: "추가 실패 - 사용자 정의 필드가 잘못됨"
          nullable: true
        failInvalidSubscriberStatus:
          type: array
          items:
            type: string
          description: "추가 실패 - 구독 상태가 잘못됨"
          nullable: true
    BatchSubscriberErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - stberror.Errors.Data.TooLongData
            - stberror.Errors.List.TooManySubscribers
          description: 에러 코드
        message:
          type: string
          description: 에러 메시지 상세
          example: "한번에 너무 많은 구독자를 요청함. (최대 1,000명)"
    ListSenderVerificationErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - stberror.Errors.List.NotExistEmail
          description: 에러 코드
          example: "stberror.Errors.List.NotExistEmail"
        message:
          type: string
          description: 에러 메시지
          example: "주소록에 추가되어있지 않은 발신자 이메일 주소로 발송을 요청함."
    UpdateEmailRequest:
      type: object
      properties:
        type:
          type: integer
          description: 이메일 타입
          example: 1
        subType:
          type: integer
          description: 이메일 서브타입
          example: 2
        abRatio:
          type: integer
          description: A/B 테스트 비율
          minimum: 0
          maximum: 100
          example: 60
        subject:
          type: string
          description: 이메일 제목
          example: "Email Subject"
        subjectA:
          type: string
          description: A/B 테스트용 A 제목
          example: "Subject A"
        subjectB:
          type: string
          description: A/B 테스트용 B 제목
          example: "Subject B"
        senderEmail:
          type: string
          format: email
          description: 발신자 이메일
          example: "sender@example.com"
        senderName:
          type: string
          description: 발신자 이름
          example: "Sender Name"
        senderNameA:
          type: string
          description: A/B 테스트용 A 발신자 이름
          example: "Sender Name A"
        senderNameB:
          type: string
          description: A/B 테스트용 B 발신자 이름
          example: "Sender Name B"
        listId:
          type: integer
          description: 주소록 아이디
          example: 123
        segmentIds:
          type: array
          description: 세그먼트 아이디 목록
          items:
            type: integer
          example: [1, 2, 3]
        groupIds:
          type: array
          description: 그룹 아이디 목록
          items:
            type: integer
          example: [4, 5, 6]
    UpdateEmailErrorResponse:
      type: object
      properties:
        code:
          type: string
          enum:
            - stberror.Errors.Email.WrongStatus
          description: 에러 코드
          example: "stberror.Errors.Email.WrongStatus"
        message:
          type: string
          description: 에러 메시지
          example: "작성 중 상태(status 0)가 아님."
    EmailLogsResponse:
      type: object
      properties:
        total:
          type: integer
          description: 전체 아이템 개수
          example: 8
        offset:
          type: integer
          description: 현재 페이지 시작 인덱스
          example: 0
        limit:
          type: integer
          description: 페이지당 아이템 개수
          example: 8
        items:
          type: array
          description: 로그 아이템 목록
          items:
            $ref: '#/components/schemas/EmailLogItem'
          example:
            - id: 1
              subscriber: "gildong.go@stibee.com"
              action: "P"
              value: ""
              value2: "250\nok"
              createdTime: "2024-07-23T18:43:08+09:00"
    EmailLogItem:
      type: object
      properties:
        id:
          type: integer
          description: 로그 아이디
          example: 1
        subscriber:
          type: string
          format: email
          description: 구독자 이메일
          example: "gildong.go@stibee.com"
        action:
          type: string
          description: |
            구독자 활동
            - P : 발송 성공
            - F : 발송 실패(소프트바운스)
            - A : 발송 실패(하드바운스)
            - D : 수신 거부
            - O : 이메일 오픈
            - C : 이메일 본문 내 링크 클릭
          enum: [P, F, A, D, O, C]
          example: "P"
        value:
          type: string
          description: |
            구독자 활동별 값
            - action이 O이면, UserAgent 정보
            - action이 C이면, 클릭한 URL
          example: ""
        value2:
          type: string
          description: |
            구독자 활동별 보조 값
            - action이 C이면, UserAgent 정보
            - action이 P, F, A이면, 발송 성공/실패 서버 응답값
          example: "250\nok"
        createdTime:
          type: string
          format: date-time
          description: 구독자 활동 생성 시간
          example: "2024-07-23T18:43:08+09:00"
          
    CreateEmailRequest:
      type: object
      properties:
        subject:
          type: string
          description: 이메일 제목
        senderEmail:
          type: string
          format: email
          description: 발신자 이메일 주소
        senderName:
          type: string
          description: 발신자 이름
        listId:
          type: integer
          description: 발송 대상 주소록
        segmentIds:
          type: array
          items:
            type: integer
          description: 발송 대상 세그먼트
        groupIds:
          type: array
          items:
            type: integer
          description: 발송 대상 그룹
    AddSubscriberRequest:
      type: object
      required:
        - subscriber
      properties:
        subscriber:
          type: object
          required:
            - email
            - status
            - fields
          properties:
            email:
              type: string
              format: email
              description: 구독자 이메일 주소
            status:
              type: string
              enum: [subscribed, unsubscribed]
              description: |
                구독자 상태
                * subscribed: 구독 중
                * unsubscribed: 수신거부
            fields:
              type: object
              description: 주소록에 생성된 사용자 정의 필드별 값 (주소록에 생성되어있는 필드만 값을 입력할 수 있음)
              example:
                name: "고길동"
                age: 45
        updateEnabled:
          type: boolean
          default: false
          description: 구독자가 이미 존재할 경우 fields 값들의 업데이트 여부. false이면 업데이트하지 않음. true이면 새로 요청한 값으로 업데이트함.
    ErrorResponse:
      type: object
      description: ""
      required:
        - code
        - httpStatusCode
      properties:
        code:
          type: string
          description: 에러 코드
        httpStatusCode:
          type: integer
          description: HTTP 상태 코드
          example: 400
    GetListResponse:
      type: object
      properties:
        id:
          type: integer
          description: 주소록 아이디
        owner:
          type: string
          format: uuid
          description: 주소록 소유자 아이디
        name:
          type: string
          description: 주소록 이름
        senderName:
          type: string
          description: 발신자 이름
        companyName:
          type: string
          description: 회사 이름
        companyContact:
          type: string
          description: 회사 연락처
        companyAddress:
          type: string
          description: 회사 주소
        useSubscriberAutoDelete:
          type: boolean
          description: 하드바운드 시 구독자 자동삭제 여부
        canSendToUnsubscribed:
          type: boolean
          description: 이메일 발송 시 수신거부 구독자 포함 가능 여부
    UpdateListRequest:
      type: object
      required:
        - name
        - senderName
        - companyName
        - companyContact
        - companyAddress
      properties:
        name:
          type: string
          description: 주소록 이름
        senderName:
          type: string
          description: 발신자 이름
        companyName:
          type: string
          description: 회사 이름
        companyContact:
          type: string
          description: 회사 연락처
        companyAddress:
          type: string
          description: 회사 주소
        useSubscriberAutoDelete:
          type: boolean
          description: 하드바운드 시 구독자 자동삭제 여부
          default: true
        canSendToUnsubscribed:
          type: boolean
          description: 이메일 발송 시 수신거부 구독자 포함 가능 여부
          default: false
    SendDoubleOptinRequest:
      type: object
      required:
        - subscriber
      properties:
        subscriber:
          type: object
          required:
            - email
            - fields
          properties:
            email:
              type: string
              format: email
              description: 구독자 이메일 주소
            fields:
              type: object
              description: 주소록에 생성된 사용자 정의 필드별 값 (주소록에 생성되어있는 필드만 값을 입력할 수 있음)
              example:
                name: "고길동"
                age: 45
    GetSubscribersResponse:
      type: object
      properties:
        email:
          type: string
          format: email
          description: 구독자 이메일
        status:
          type: string
          description: 구독자 구독 상태
        fields:
          type: object
          description: 사용자 정의 필드 값
          additionalProperties: true
          example:
            $ad_agreed: ""
            age: "43"
            name: "고길동"
        createdTime:
          type: string
          description: 구독일
          example: "2024-11-12 17:09:13 +0900 KST"
        modifiedTime:
          type: string
          description: 수정일
          example: "2024-11-17 20:01:11 +0900 KST"
    GetSubscriberCountResponse:
      type: object
      required:
        - total
      properties:
        total:
          type: integer
          description: 전체 구독자 수
          example: 1234
    UpdateSubscriberResponse:
      type: object
      properties:
        createdSubscribers:
          type: array
          items:
            type: string
          description: 새로 생성된 구독자 이메일 목록
        updatedSubscribers:
          type: array
          items:
            type: string
          description: 업데이트된 구독자 이메일 목록
        failNoEmails:
          type: array
          items:
            type: string
          nullable: true
          description: 이메일이 누락된 실패 목록
        failInvalidEmails:
          type: array
          items:
            type: string
          nullable: true
          description: 유효하지 않은 이메일 형식으로 인한 실패 목록
        failDuplicatedEmails:
          type: array
          items:
            type: string
          nullable: true
          description: 중복된 이메일로 인한 실패 목록
        failInvalidFields:
          type: array
          items:
            type: string
          nullable: true
          description: 유효하지 않은 필드로 인한 실패 목록
        failInvalidSubscriberStatus:
          type: array
          items:
            type: string
          nullable: true
          description: 유효하지 않은 구독자 상태로 인한 실패 목록
        failAlreadyExists:
          type: array
          items:
            type: string
          nullable: true
          description: 이미 존재하는 구독자로 인한 실패 목록
    UpdateSubscriberRequest:
      type: object
      required:
        - fields
      properties:
        fields:
          type: object
          description: 주소록에 생성된 사용자 정의 필드별 값 (주소록에 생성되어있는 필드만 값을 입력할 수 있음)
          example:
            name: "고길동"
            age: 45
    AssignGroupRequest:
      type: object
      required:
        - subscriber
      properties:
        subscriber:
          type: string
          format: email
          description: 구독자 이메일
          example: "gildong.go@stibee.com"
    ReleaseGroupRequest:
      type: object
      required:
        - subscriber
      properties:
        subscriber:
          type: string
          format: email
          description: 구독자 이메일
          example: "gildong.go@stibee.com"
    DeleteSubscribersRequest:
      type: object
      required:
        - subscribers
      properties:
        subscribers:
          type: array
          description: |
            삭제할 구독자 이메일 목록
            * 한번에 최대 요청할 수 있는 개수는 100명
          items:
            type: string
            format: email
          maxItems: 100
          example: ["email1", "email2"]
    GetListSenderResponse:
      type: object
      properties:
        email:
          type: string
          format: email
          description: 발신자 이메일 주소
          example: "gildong.go@stibee.com"
        authorized:
          type: boolean
          description: "발신자 이메일의 인증 여부. false 이면 “email”로 수신된 인증메일을 통해 발신자 인증을 수행해야한다."
          example: false
    CreateGroupRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 그룹 이름
          example: "그룹A"
    CreateGroupResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: 그룹 아이디
          example: 1234
    GetGroupResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            description: 그룹 아이디
          name:
            type: string
            description: 그룹 이름
          createdTime:
            type: string
            format: date-time
            description: 생성 일시
            example: "2024-11-17T22:20:35+09:00"
    UpdateGroupRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 그룹 이름
          example: "그룹A"
